<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dominio_J.iary\Dominio_J.iary.csproj" />
    <ProjectReference Include="..\Infra_BancoDadosORM_J.iary\Infra_BancoDadosORM_J.iary.csproj" />
  </ItemGroup>

</Project>
